# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_testing',
                'doc_host': 'https://mineshkumar.github.io',
                'git_url': 'https://github.com/mineshkumar/nbdev_testing',
                'lib_path': 'nbdev_testing'},
  'syms': {'nbdev_testing.core': {'nbdev_testing.core.foo': ('core.html#foo', 'nbdev_testing/core.py')}}}
